# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_auto_20160323_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='anger_level',
            field=models.IntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='anxiety_level',
            field=models.IntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='energy_level',
            field=models.IntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='happiness_level',
            field=models.IntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='motivation_level',
            field=models.IntegerField(choices=[(-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
    ]
