# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0009_auto_20160323_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
