# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0010_auto_20160324_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
