# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0013_auto_20160324_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 24, 20, 50, 35, 209261, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 24, 20, 50, 41, 137057, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
