# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0014_auto_20160324_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
