# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0015_auto_20160405_1808'),
        ('mood', '0015_auto_20160403_1358'),
    ]

    operations = [
    ]
