# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0020_auto_20160418_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.CharField(default='asd', max_length=75),
            preserve_default=False,
        ),
    ]
